// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDBGrVPwHFh3gNs_AXY7o1lFfsBw_1B00',
    appId: '1:1012060339384:web:2d4cceffb2f8ed8dcac84d',
    messagingSenderId: '1012060339384',
    projectId: 'aiaprtd-member',
    authDomain: 'aiaprtd-member.firebaseapp.com',
    databaseURL: 'https://aiaprtd-member-default-rtdb.firebaseio.com',
    storageBucket: 'aiaprtd-member.firebasestorage.app',
    measurementId: 'G-YZ9MZ3LF8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlq6b4elQt8tff-dhSSujgl7iaYA9Lsc',
    appId: '1:1012060339384:android:69e4b898830c9658cac84d',
    messagingSenderId: '1012060339384',
    projectId: 'aiaprtd-member',
    databaseURL: 'https://aiaprtd-member-default-rtdb.firebaseio.com',
    storageBucket: 'aiaprtd-member.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA11F9-bi4OoRzNWhsZqkiazDNq4tEyxJQ',
    appId: '1:1012060339384:ios:7ed3c6497a7141f1cac84d',
    messagingSenderId: '1012060339384',
    projectId: 'aiaprtd-member',
    databaseURL: 'https://aiaprtd-member-default-rtdb.firebaseio.com',
    storageBucket: 'aiaprtd-member.firebasestorage.app',
    iosClientId: '1012060339384-5fvebu52t08jprb81ou27hleufkqda1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiaprtdAdminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA11F9-bi4OoRzNWhsZqkiazDNq4tEyxJQ',
    appId: '1:1012060339384:ios:7ed3c6497a7141f1cac84d',
    messagingSenderId: '1012060339384',
    projectId: 'aiaprtd-member',
    databaseURL: 'https://aiaprtd-member-default-rtdb.firebaseio.com',
    storageBucket: 'aiaprtd-member.firebasestorage.app',
    iosClientId: '1012060339384-5fvebu52t08jprb81ou27hleufkqda1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiaprtdAdminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDBGrVPwHFh3gNs_AXY7o1lFfsBw_1B00',
    appId: '1:1012060339384:web:7c65788c6fac3e37cac84d',
    messagingSenderId: '1012060339384',
    projectId: 'aiaprtd-member',
    authDomain: 'aiaprtd-member.firebaseapp.com',
    databaseURL: 'https://aiaprtd-member-default-rtdb.firebaseio.com',
    storageBucket: 'aiaprtd-member.firebasestorage.app',
    measurementId: 'G-T9R1TD8W1X',
  );
}
